# Default redirection
default-redirect: "https://buy.soulmc.top/"

# Additional redirections
# page name: "redirect url"
redirects:
  discord: "https://discord.gg/PHJZYYawVV"
  vk: "https://vk.com/soullandsbe/"